### ISSUE TITLE
"Arguments" and "command" in one entry are allowed?

### ISSUE THREAD

**Issue by TarasBereznyak** [rizsotto/json_compilation_db#9]
Looking at the code, I see strange thing: there is a check that we can't have two "command" or two "argument" keys (but why we need it, JSON format restrict it anyway), but there is not a check that we have one "command" and "argument" keys. It is very strange possibility. And in this case we get only "arguments".

**Comment by rizsotto** [comment]
Hey @TarasBereznyak , thanks to raise this issue. Can you show me an input JSON which is parsed incorrectly? I am not sure if I understand your description of the problem, and an example would help to clarify that.
